apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: test-logger
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: test-logger
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: test-logger
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      containers:
      - name: fluentd
        image: abhishekdhariwal/fluentd_minio_plugin:v6
        imagePullPolicy: IfNotPresent
        env:
          - name: AWS_ACEESS_KEY_ID
            value: "minio"
          - name: AWS_ACCESS_SECRET_KEY
            value: "minio123"
          - name: S3_BUCKET_NAME
            value: "iris-s3"
          - name: S3_ENDPOINT
            value: "http://10.174.134.66:32606"
        resources:
          requests:
            cpu: 200m
            memory: 0.5Gi
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: homedockercontainers
          mountPath: /home/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: homedockercontainers
        hostPath:
          path: /home/docker/containers
